const DATA=[
["word-to-pdf","Word ↔ PDF","Documents & PDF","Convert DOCX and PDF through the governed job contract.","HEAVY","QUEUE"],
["pdf-merge-split","Merge / Split / Rotate","Documents & PDF","Reorder pages, split ranges and rotate documents.","HEAVY","QUEUE"],
["pdf-compress","Compress PDF","Documents & PDF","Reduce file size with a controlled output artifact.","HEAVY","QUEUE"],
["pdf-ocr-fa","OCR فارسی + English","Documents & PDF","Extract searchable text from scanned documents.","HEAVY","QUEUE"],
["pdf-image","PDF ↔ Image","Documents & PDF","Render pages or assemble images into a PDF.","HEAVY","QUEUE"],
["remove-background","Remove background","Images","rembg-backed background removal.","HEAVY","QUEUE"],
["passport-photo","Passport photo","Images","Crop and prepare ID photos against defined presets.","HEAVY","QUEUE"],
["image-resize-compress","Resize + compress","Images","Resize images locally without upload.","LIGHT","BROWSER"],
["image-convert","Convert format","Images","Convert common browser-supported formats locally.","LIGHT","BROWSER"],
["extract-audio","Extract audio","Audio & Video","yt-dlp + FFmpeg contract for authorized media URLs.","HEAVY","QUEUE"],
["media-convert","Media conversion","Audio & Video","Convert audio and video through an isolated worker.","HEAVY","QUEUE"],
["whisper-transcribe","Whisper transcription","Audio & Video","Speech-to-text with language-aware output.","HEAVY","QUEUE"],
["qr-code","QR Code","Quick Utilities","Generate a QR locally in the browser.","LIGHT","BROWSER"],
["word-counter","Word counter","Quick Utilities","Count words, characters and lines locally.","LIGHT","BROWSER"],
["password-generator","Password generator","Quick Utilities","Generate strong passwords locally.","LIGHT","BROWSER"]];
const tree=document.getElementById("tree"),cards=document.getElementById("cards"),panel=document.getElementById("toolPanel"),search=document.getElementById("search"),count=document.getElementById("resultCount"),sidebar=document.querySelector(".sidebar");
function render(q=""){q=q.trim().toLowerCase();const rows=DATA.filter(x=>!q||x.join(" ").toLowerCase().includes(q));cards.innerHTML=rows.map((x)=>'<article class="card" data-id="'+x[0]+'"><span class="num">'+String(DATA.indexOf(x)+1).padStart(2,"0")+'</span><span class="mode">'+x[5]+'</span><h3>'+x[1]+'</h3><p>'+x[3]+'</p></article>').join("");count.textContent=rows.length+" tools";cards.querySelectorAll(".card").forEach(c=>c.onclick=()=>select(c.dataset.id));tree.querySelectorAll("[data-tool]").forEach(a=>a.hidden=!!q&&!a.textContent.toLowerCase().includes(q));}
function select(id){const x=DATA.find(d=>d[0]===id);if(!x)return;history.replaceState(null,"","#"+id);tree.querySelectorAll("[data-tool]").forEach(a=>a.classList.toggle("active",a.dataset.tool===id));cards.querySelectorAll(".card").forEach(c=>c.classList.toggle("selected",c.dataset.id===id));panel.innerHTML='<div><span class="panel-kicker">'+x[2].toUpperCase()+" / "+x[5]+'</span><h2>'+x[1]+'</h2><p>'+x[3]+'</p><button class="open-btn" id="openTool">OPEN TOOL</button></div><div class="panel-side"><div class="spec"><span>MODE</span><b>'+x[4]+'</b></div><div class="spec"><span>ROUTE</span><b>'+(x[4]==="LIGHT"?"LOCAL":"QUEUE")+'</b></div><div class="spec"><span>STATUS</span><b>CATALOG READY</b></div><div class="spec"><span>SLUG</span><b>'+x[0]+'</b></div></div>';document.getElementById("openTool").onclick=()=>openTool(x);if(innerWidth<760)sidebar.classList.remove("open");}
function openTool(x){const d=document.createElement("dialog");d.innerHTML='<div class="dialog-head"><span class="panel-kicker">'+x[2].toUpperCase()+" / "+x[5]+'</span><button>×</button></div><div class="dialog-body"><h3>'+x[1]+'</h3><p>'+x[3]+'</p><div class="result">'+(x[4]==="LIGHT"?"MODE: BROWSER / LOCAL\nEXECUTION: SAFE-LOCAL":"QUEUE CONTRACT: READY\nAUTHORIZATION + QUOTA + ISOLATION\nEXECUTION API: /api/tools/"+x[0]+"/execute\nSTATUS: SCAFFOLD — NOT YET DEPLOYED")+'</div></div>';document.body.appendChild(d);d.showModal();d.querySelector("button").onclick=()=>d.close();d.addEventListener("close",()=>d.remove());}
tree.querySelectorAll(".tree-head").forEach(h=>h.onclick=()=>h.parentElement.classList.toggle("closed"));tree.querySelectorAll("[data-tool]").forEach(a=>a.onclick=()=>select(a.dataset.tool));search.oninput=()=>render(search.value);document.getElementById("collapseAll").onclick=()=>document.querySelectorAll(".tree-group").forEach(g=>g.classList.add("closed"));document.getElementById("mobileMenu").onclick=()=>sidebar.classList.toggle("open");render();select(location.hash.slice(1)||"word-to-pdf");